### ISSUE TITLE
Wrong vulnerability detection

### ISSUE THREAD

**Issue by dbrgn** [RustSec/cargo-audit#17]
cargo-audit thinks hyper 0.12.0-pre.0 is vulnerable to RUSTSEC-2017-0002:

```
    Fetching advisories `https://raw.githubusercontent.com/RustSec/advisory-db/master/Advisories.toml`
    Scanning 160 crates for vulnerabilities (5 advisories in database)
     Warning Vulnerable crates found!

ID: RUSTSEC-2017-0002
Crate: hyper
Version: 0.12.0-pre.0
Date: 2017-01-23
URL: https://github.com/hyperium/hyper/wiki/Security-001
Title: headers containing newline characters can split messages
Solution: upgrade to: >= 0.10.2, < 0.10.0, >= 0.9.18
```

Maybe wrong version comparison due to the "-pre.0" suffix?

**Comment by tarcieri** [comment]
Matching is performed using the [semver crate](https://github.com/steveklabnik/semver). See:

https://github.com/RustSec/rustsec-client/blob/master/src/db.rs#L105

So either:

1. The version expression in the hyper advisory is wrong -or-
2. There is a bug in the semver crate

**Comment by dbrgn** [comment]
I assume this is a semver bug, see https://github.com/steveklabnik/semver/issues/172

**Comment by tarcieri** [comment]
Per the discussion on https://github.com/steveklabnik/semver/issues/172 I'm not sure this is fixed, but I'm closing it because it should be filed against rustsec-client:

https://github.com/RustSec/rustsec-client

That said, I'm not sure this can or should be fixed upstream in `semver`, and instead the `rustsec` crate may need to implement special matching logic for prerelease crates.
